INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (1, '10.4.1', '意外走火', '向不安全的方向射擊', '投射物射越後擋彈坡、護堤或主辦單位在書面賽程簡報中釐定為不安全的方向。注意如參 賽者合理地射擊標靶，但投射物射向不安全方向，不可判取消參賽資格，但可引用賽例2.3修正 賽程。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (2, '10.4.2', '意外走火', '向3米內的地面射擊', '投射物擊中離參賽者3米內地面（射擊設置於3米內的紙靶除外）。因沒有足夠推動投射 物氣體而導致投射物擊落於離參賽者3米內地面的情况豁免引用此賽例。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (4, '10.4.3', '意外走火', '上匣，換匣，卸匣時走火', '鎗枝上匣，換匣，卸匣時射出投射物。此情況包括任何於賽例8.3.1至8.3.7所列出動作中 發生的響鎗(亦見賽例10.5.10)。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (5, '10.4.4', '意外走火', '維修時走火', '維修故障鎗枝時射出投射物。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (6, '10.4.5', '意外走火', '換手時走火', '換手持鎗時鎗枝射出投射物。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (7, '10.4.6', '意外走火', '移動時走火', '移動時鎗枝射出投射物，射擊標靶時除外。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (8, '10.4.7', '意外走火', '在不安全距離射擊剛性物料靶', '在不安全距離（2米）射擊剛性物料靶(見賽例2.1.3)。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (9, '10.5.2', '不安全使用鎗枝', '槍口指向超過180度', '鎗口指向超過賽程容許或指定的安全射擊角度，(有限制的豁免:見賽例 2.1.2.1， 5.2.7.3 及 10.5.7)。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (11, '10.5.3', '不安全使用鎗枝', '掉鎗', '參賽者在賽程進行中任何時間掉下鎗枝或導致鎗枝掉下(不論鎗枝有否入匣)。如參賽者因任何理由，在賽程進行中有意識及安全地將鎗枝放於地上或其他牢固物件上不能判取消參賽資格，例如：\n參賽者仍然緊持鎗枝直至鎗枝穩固和安全地放於地上或其他牢固物件上，\n參賽者在任何時間均保持鎗枝在自身1米範圍內(鎗枝在RO監督下放於遠處作開始準備情況除外)，\n不干犯賽例10.5.2規定，\n鎗枝按賽例8.1規定的準備狀態下，\n鎗枝在未有上匣的狀態及滑架於後定位置。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (12, '10.5.4', '不安全使用鎗枝', '隧道內拔鎗或Holster', '在隧道範圍內拔鎗或將鎗枝放回鎗套。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (13, '10.5.5', '不安全使用鎗枝', '槍口指向身體', '鎗口在賽程進行中指向身體任何部分。參賽者於拔鎗和把鎗枝放回鎗套時指向身體部分或 依賽例8.3.6.1清空鎗膛，但扣板機的手指明顯移離扳機護環，不可判取消參賽資格。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (14, '10.5.6', '不安全使用鎗枝', '鎗口指向其他人', '於賽程時鎗枝鎗口指向其他人(例如比賽工作人員或觀眾)身體任何部位。不適用於參賽者 已遵從賽例8.5.6，於賽程期間任何意外出現於賽程射擊範圍內人士的情況。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (15, '10.5.7', '不安全使用鎗枝', '鎗枝鎗口指向超越參賽者脚下後 方半徑1米', '於拔鎗和把鎗枝放回鎗套時，已上膛/入匣(裝有投射物)的鎗枝鎗口指向超越參賽者脚下後 方半徑1米。此1米寬限僅適用於參賽者正面面對射擊場。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (16, '10.5.8', '不安全使用鎗枝', '進行賽程時佩帶或使用多於一把鎗枝。', '進行賽程時佩帶或使用多於一把鎗枝。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (17, '10.5.9', '不安全使用鎗枝', '維修時，槍支移離標靶時手指在護環內', '參賽者鎗枝明顯移離標靶進行維修時，扣板機的手指仍放於板機護環內。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (18, '10.5.10', '不安全使用鎗枝', '上匣、換匣、或卸匣時，手指在護環內', '在上匣、換匣、或卸匣時，扣板機的手指仍放於板機護環內，特別情況允許除外(見賽 例 8.1.2.5，8.3.7.1 及 8.7.1)。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (19, '10.5.11', '不安全使用鎗枝', '移動時，手指在護環內', '跟據賽例8.5.1，移動時扣板機的手指仍放於板機護環內。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (21, '10.5.12', '不安全使用鎗枝', '在槍套內的已上膛的槍支沒有啟動安全掣', '在下列任何情況下，已上膛/入匣(裝有投射物)的鎗枝放於鎗套內：\n單動作半自動鎗枝已上膛，但沒有啟動安全掣。\n雙動作或選擇式半自動鎗枝已拉起擊鎚，但沒有啟動安全掣。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (22, '10.5.13', '不安全使用鎗枝', '在安全區內手持投射物或任何裝有壓縮氣體的東西', '在安全區內手持投射物或任何裝有壓縮氣體的東西，違反賽例2.4.4。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (24, '10.5.14', '不安全使用鎗枝', '自行擁有已上膛/入匣的槍支', '未有 RO的授權下擁有已上膛/入匣(裝有投射物)的鎗枝。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (25, '10.5.15', '不安全使用鎗枝', '拾起掉倒地上鎗枝', '拾起掉倒地上鎗枝。掉倒地上鎗枝必須經由RO拾起，在檢查和/或清空鎗枝後，直接放回參賽者的鎗盒、鎗袋或鎗套。在賽程進行以外時間，掉下未有入匣的鎗枝或導致鎗枝掉下不會判罰取消參賽資格。然而，如參賽者自行拾回掉下的鎗枝將被判罰取消參賽資格。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (26, '10.5.16', '不安全使用鎗枝', '使用非法的投射物或槍支', '使用被禁止和/或不安全的投射物(見賽例5.5.4，5.5.6及5.6.1)，和/或使用被禁止的鎗枝(見 賽例5.1.10及5.1.11)。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (27, '10.6.1', '違背體育精神行為', '參賽者做出違背體育精神行為', 'RO 可基於參賽者做出違背體育精神行為時判罰取消參賽資格。例子包括，但不只限於：作弊、不誠實、不服從比賽工作人員合理的指示，或做出任何玷污比賽的行為。必須盡快向RM報告。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (28, '10.6.2', '違背體育精神行為', '故意使護目鏡脫下', '如 RO認為參賽者故意脫下或導致護目鏡脫下，從而希望獲得重賽或得益，會判罰該參賽者取消參賽資格。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (29, '10.6.3', '違背體育精神行為', '在場人仕做出不可接受的行為', '如 RO認為任何在場人仕做出不可接受的行為時，可將該等人仕驅逐離場。不可接受的行為包括，但不只限於：不服從比賽工作人員合理的指示、干擾比賽運作和/或參賽者作賽，及做出任何玷污比賽的行為。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (30, '10.7.2', '嚴禁使用的物品', '參賽者濫用酒精製品、禁藥或藥物', 'IPSC 嚴禁參賽者濫用酒精製品、非處方和不必要的藥物及服用禁藥或增强身體機能的藥物，不論如何使用或管有，皆為嚴重違規的行為。');
INSERT INTO public."DqObject" (id, index, category, title, description) VALUES (31, '10.7.3', '嚴禁使用的物品', '參賽者受藥物作用影響', '在 IPSC比賽中，除醫藥用途外，參賽者及工作人員均不能受任何藥物(包括洒精製品)影響。如RM認為任何人仕明顯受上述物品影響，將判罰取消參賽資格及有權將該等人仕驅逐離場。');
