name: Node.js CI

on: [push]

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run gen
      - run: npm run build
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          path: |
            build/
            package.json
            package-lock.json