name: Node.js CI

on: [push]

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run gen
      - run: npm run build
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: build-server
          path: |
                build/
                package.json
                package-lock.json
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          prerelease: true
          tag: "latest-build"
          makeLatest: true
          generateReleaseNotes: true
          artifacts: "build-server"