name: Node.js CI

on: [push]

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write
  packages: write
  deployments: write
  id-token: write
  attestations: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run gen
      - run: npm run build
      - run: zip -r "server.zip" "build/" "package.json" "package-lock.json"
      - name: "Upload Release Asset"
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "server.zip"
          # prerelease: true
          # generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          # name: Release ${{ github.ref_name }}-${{github.sha}}
          # token: ${{ env.GITHUB_TOKEN }}