name: Node.js CI

on: [push]

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write
  packages: write
  deployments: write
  id-token: write
  attestations: write

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run gen
      - run: npm run build
      - run: zip -r "server.zip" "build/" "package.json" "package-lock.json"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}/${{github.workflow_ref}}
          generate_release_notes: true
          files: server.zip
          token: ${{ secrets.GITHUB_TOKEN }}