name: Node.js CI

on: [push]

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run gen
      - run: npm run build
      - run: zip -r "server.zip" "build/" "package.json" "package-lock.json"
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: server.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}